on:
  push:
  pull_request:
  release:
    types:
      - created

name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install
        run:  make install
      - name: update version of packages/@dcl/rollup-config
        uses: menduz/oddish-action@staging
        with:
          cwd: packages/@dcl/rollup-config
          deterministic-snapshot: true
          only-update-versions: true
      - name: update version of packages/build-ecs
        uses: menduz/oddish-action@staging
        with:
          cwd: packages/build-ecs
          deterministic-snapshot: true
          only-update-versions: true
      - name: update version of packages/decentraland-amd
        uses: menduz/oddish-action@staging
        with:
          cwd: packages/decentraland-amd
          deterministic-snapshot: true
          only-update-versions: true
      - name: update version of packages/decentraland-ecs
        uses: menduz/oddish-action@staging
        with:
          cwd: packages/decentraland-ecs
          deterministic-snapshot: true
          only-update-versions: true
      - name: build
        run:  make build
      - name: test
        run:  make test
