on:
  push:
  pull_request:
  release:
    types:
      - created

name: CI
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Use Node.js 14.x
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - name: install
        run: make install
      - name: update version of packages/@dcl/dcl-rollup
        uses: menduz/oddish-action@staging
        with:
          cwd: packages/@dcl/dcl-rollup
          deterministic-snapshot: true
          only-update-versions: true
      - name: update version of packages/@dcl/build-ecs
        uses: menduz/oddish-action@staging
        with:
          cwd: packages/@dcl/build-ecs
          deterministic-snapshot: true
          only-update-versions: true
      - name: update version of packages/@dcl/amd
        uses: menduz/oddish-action@staging
        with:
          cwd: packages/@dcl/amd
          deterministic-snapshot: true
          only-update-versions: true
      - name: update version of packages/decentraland-ecs
        uses: menduz/oddish-action@staging
        with:
          cwd: packages/decentraland-ecs
          deterministic-snapshot: true
          only-update-versions: true
      - name: build
        run: make build
      - name: test
        run: make test
      - name: prepare releasable packages
        run: make prepare
